// Demo data for testing without database
import { ProductComplaint, BatchRiskRegistry } from '@/types/complaints';

export const DEMO_COMPLAINTS: ProductComplaint[] = [
  {
    id: '1',
    user_id: 'demo-farmer-1',
    verification_id: 'verify-1',
    batch_number: 'RICE-2024-001',
    brand_name: 'GreenSeeds Ltd',
    crop_type: 'Paddy',
    district: 'District A',
    issue_type: 'poor_germination',
    description: 'Only 40% of seeds germinated in my field',
    days_since_sowing: 14,
    severity_score: 4,
    field_image_url: null,
    status: 'open',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    user_id: 'demo-farmer-1',
    verification_id: null,
    batch_number: 'RICE-2024-001',
    brand_name: 'GreenSeeds Ltd',
    crop_type: 'Paddy',
    district: 'District B',
    issue_type: 'stunted_growth',
    description: 'Plants are significantly smaller than expected',
    days_since_sowing: 21,
    severity_score: 3,
    field_image_url: null,
    status: 'investigating',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    user_id: 'demo-farmer-2',
    verification_id: null,
    batch_number: 'RICE-2024-001',
    brand_name: 'GreenSeeds Ltd',
    crop_type: 'Paddy',
    district: 'District A',
    issue_type: 'no_yield',
    description: 'No productive yield from the entire field',
    days_since_sowing: 45,
    severity_score: 5,
    field_image_url: null,
    status: 'investigating',
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    user_id: 'demo-farmer-3',
    verification_id: null,
    batch_number: 'RICE-2024-001',
    brand_name: 'GreenSeeds Ltd',
    crop_type: 'Paddy',
    district: 'District C',
    issue_type: 'pest_susceptibility',
    description: 'Plants highly susceptible to armyworm infestation',
    days_since_sowing: 25,
    severity_score: 4,
    field_image_url: null,
    status: 'open',
    created_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    user_id: 'demo-farmer-2',
    verification_id: null,
    batch_number: 'RICE-2024-001',
    brand_name: 'GreenSeeds Ltd',
    crop_type: 'Paddy',
    district: 'District B',
    issue_type: 'poor_germination',
    description: 'Very poor germination rate across the field',
    days_since_sowing: 10,
    severity_score: 5,
    field_image_url: null,
    status: 'open',
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    user_id: 'demo-farmer-4',
    verification_id: null,
    batch_number: 'WHEAT-2024-002',
    brand_name: 'HarvestPro Seeds',
    crop_type: 'Wheat',
    district: 'District D',
    issue_type: 'stunted_growth',
    description: 'Stunted growth compared to previous seasons',
    days_since_sowing: 20,
    severity_score: 2,
    field_image_url: null,
    status: 'open',
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_BATCH_REGISTRY: BatchRiskRegistry[] = [
  {
    batch_number: 'RICE-2024-001',
    brand_name: 'GreenSeeds Ltd',
    total_complaints: 5,
    unique_districts: 3,
    risk_level: 'high_risk',
    last_complaint_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    batch_number: 'WHEAT-2024-002',
    brand_name: 'HarvestPro Seeds',
    total_complaints: 1,
    unique_districts: 1,
    risk_level: 'normal',
    last_complaint_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    batch_number: 'CORN-2024-003',
    brand_name: 'AgriBest Ltd',
    total_complaints: 3,
    unique_districts: 2,
    risk_level: 'suspicious',
    last_complaint_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DEMO_COMPLAINT_STATS = {
  highRiskBatchesCount: 1,
  todayComplaintsCount: 2,
  worstPerformingDistrict: 'District A',
};
